### ISSUE TITLE
Hi, my transaction has never been confirmed

### ISSUE THREAD

**Issue by HebeBlock** [ravencoinclassicio/RavencoinClassic#4]
https://explorer.ravencoinclassic.io/tx/cacc66e5c3cfd566ba83f093f6c2b7e0a619da9315f813351374168abd1e30b4

https://explorer.ravencoinclassic.io/tx/10ca8fc24064a1743debea48570516d7075bcfc2b086abc3c32a846cc94139ca

I am using ravencore-lib

**Comment by HebeBlock** [comment]
hex: 010000000195809147571cf1fd829cd3473a7cfb28aef09ffd960ef225fa27e93b581941fa010000006b483045022100fd5bea14ed596c46e2e00b419cdde335f9667366bd81e56ec22d1dbeba4d5ad2022027713741ec5d5e14cbd1783a9ce5c9dcdea7f1d21e7350c71301183eb0e5be13012102b51117ca8b6b0de630f42763a2be1b1ce7fe322ae750ee8d4eaaaf65ed7aeb5affffffff0200ca9a3b000000001976a9147bfb6527e7e3f95cf3b009068483176b86de130d88accd436bee020000001976a9147655255f2236acf50c7d724c9dbf8d97f1b7ac3b88ac00000000

txid:"fed35f38b0c343fa562acfa5596ce7806a95ee0b3cff000f0e4cc4156eca03ec"

**Comment by zsulocal** [comment]
The tx need signed with hashtype "ALL|FORKID"
